# Parse htmluseng Bautiful Soap
# @hint As data source, we use here .html files generated by 'TimePlanner' android app
# @source https://python-scripts.com/beautifulsoup-html-parsing
#!/usr/bin/python3

from bs4 import BeautifulSoup

with open("import/time_planner_logged_activities_2021-06-30.html", encoding="utf8") as f:
    contents = f.read()

    soup = BeautifulSoup(contents, 'lxml')

    cats = []
    for cat in soup.find_all("b"):
        #print("{0}".format(cat.text))
        cats.append(cat.text)

    # revert values for proper pop
    #cats = cats.sort()

    tables = soup.findAll("table", {"cellpadding": "10"})
    for table in tables:
        cat = cats.pop(0)
        print(cat)
        for row in table.findAll("tr"):
            cells = row.findAll("td")
            if len(cells) == 3:
                time = cells[0].find(text=True)
                date = cells[1].find(text=True)
                # convert date to proper format, ex: 3 авг. 2021 г. => '2020-08-03T00:00:00+03:00'
                # date_start =
                # date_end =
                name = cells[2].find(text=True)
                print("{0}\t{1}\t{2}".format(time, date, name))
